SELECT * FROM MEMBER;

--1번부터 5번까지 가져오기
--ROWNUM 오라클이 제공하는 가상컬럼을 이용
SELECT *
FROM(SELECT ROWNUM AS RNUM,M.* FROM (SELECT * FROM MEMBER ORDER BY ENROLLDATE DESC) M)
WHERE RNUM BETWEEN 6 AND 10;
